/*
 * File: app/controller/MainMenuController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vede.controller.DeviceEditor.MainMenuController', {
    extend: 'Ext.app.Controller',

    onNewDesignClick: function(button, e, options) {
        Teselagen.manager.ProjectManager.createNewDeviceEditorProject();
    },
    onOpenDEProjectClick: function(button, e, options) {

    },
    onSaveDesignClick: function(button, e, options) {

    },

    init: function() {
        this.control({
            'button[cls="newDesign"]': {
                click: this.onNewDesignClick
            },
            "#openDEProject": {
                click: this.onOpenDEProjectClick
            },
            "#saveDesign": {
                click: this.onSaveDesignClick
            }
        });

    }

});
