/*
 * File: app/controller/MainMenuController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vede.controller.DeviceEditor.MainMenuController', {
    extend: 'Ext.app.Controller',

    onNewDesignClick: function(button, e, options) {
        $(document).trigger('newDesign');
    },
    onOpenDesignClick: function(button, e, options) {
        $(document).trigger('openDesign');
    },
    onSaveDesignClick: function(button, e, options) {
        console.log('Trying save design!');
        $(document).trigger('saveDesign');
    },

    init: function() {
        this.control({
            "#newDesign": {
                click: this.onNewDesignClick
            },
            "#openDesign": {
                click: this.onOpenDesignClick
            },
            "#saveDesign": {
                click: this.onSaveDesignClick
            }
        });

    }

});
