
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Vede": "app",
  "Ext": "ext/src"
});
Ext.ClassManager.addNameAlternateMappings({

});
