/*
 * File: app/view/AppViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vesa.view.AppViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 50,
                    id: 'headerPanel',
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            id: 'headerMain',
                            items: [
                                {
                                    xtype: 'image',
                                    height: 32,
                                    id: 'headerIcon',
                                    margin: 10,
                                    width: 201,
                                    src: 'resources/images/teselagen_toplogo.png'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'panel',
                            dock: 'right',
                            id: 'headerSub',
                            layout: {
                                type: 'fit'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    styleHtmlContent: false,
                                    iconAlign: 'right',
                                    text: 'user_Name',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    region: 'west',
                    split: true,
                    id: 'projectPanel',
                    maxWidth: 230,
                    minWidth: 228,
                    width: 228,
                    collapseDirection: 'left',
                    collapsible: true,
                    frameHeader: false,
                    hideCollapseTool: false,
                    preventHeader: false,
                    title: 'Project',
                    activeTab: 0,
                    plain: false,
                    removePanelHeader: false,
                    items: [
                        {
                            xtype: 'panel',
                            id: 'projectDesignTab',
                            layout: {
                                type: 'fit'
                            },
                            minButtonWidth: 32,
                            title: '',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'projectTab1',
                                autoWidth: true,
                                icon: 'resources/images/ux/designTab.png',
                                iconCls: 'projectBarButton'
                            },
                            items: [
                                {
                                    xtype: 'treepanel',
                                    id: 'projectDesignPanel',
                                    title: 'Your Designs',
                                    viewConfig: {

                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'projectAnalysisTab',
                            layout: {
                                type: 'fit'
                            },
                            title: '',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'projectTab2',
                                icon: 'resources/images/ux/graphTab.png',
                                iconCls: 'projectBarButton'
                            },
                            items: [
                                {
                                    xtype: 'treepanel',
                                    id: 'projectAnalysisPanel',
                                    title: 'j5 Results',
                                    viewConfig: {

                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'projectPartsTab',
                            layout: {
                                type: 'fit'
                            },
                            title: '',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'projectTab3',
                                icon: 'resources/images/ux/partsTab.png',
                                iconCls: 'projectBarButton'
                            },
                            items: [
                                {
                                    xtype: 'treepanel',
                                    id: 'projectPartsPanel',
                                    title: 'Your Parts',
                                    viewConfig: {

                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'projectRegistryTab',
                            layout: {
                                type: 'fit'
                            },
                            title: '',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'projectTab4',
                                autoWidth: false,
                                icon: 'resources/images/ux/registryTab.png',
                                iconCls: 'projectBarButton'
                            },
                            items: [
                                {
                                    xtype: 'treepanel',
                                    id: 'projectsRegistryPanel',
                                    title: 'Registry',
                                    viewConfig: {

                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    id: 'mainAppPanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            title: 'Dashboard',
                            tabConfig: {
                                xtype: 'tab',
                                id: 'DashboardTab'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            layout: {
                                                type: 'fit'
                                            },
                                            title: 'My Panel'
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 2,
                                            maxHeight: 300,
                                            layout: {
                                                type: 'fit'
                                            },
                                            title: 'My Panel'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 2,
                                    maxWidth: 200,
                                    layout: {
                                        type: 'fit'
                                    },
                                    title: 'My Panel'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'VectorEditor',
                            layout: {
                                type: 'fit'
                            },
                            title: 'Vector Editor',
                            dockedItems: [
                                {
                                    xtype: 'panel',
                                    dock: 'top',
                                    id: 'MainMenuPanel',
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'toolbar',
                                            flex: 1,
                                            hidden: false,
                                            id: 'VectorEditorMenuBar',
                                            autoScroll: false,
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'File',
                                                    menu: {
                                                        xtype: 'menu',
                                                        floating: true,
                                                        minWidth: 150,
                                                        width: 120,
                                                        collapsed: false,
                                                        collapsible: false,
                                                        hideCollapseTool: false,
                                                        titleCollapse: false,
                                                        plain: false,
                                                        items: [
                                                            {
                                                                xtype: 'menuitem',
                                                                id: 'importMenuItem',
                                                                plain: false,
                                                                text: 'Import from File'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Download Genbank'
                                                            },
                                                            {
                                                                xtype: 'menuseparator'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Project Properties'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Print',
                                                                menu: {
                                                                    xtype: 'menu',
                                                                    width: 120,
                                                                    items: [
                                                                        {
                                                                            xtype: 'menuitem',
                                                                            text: 'Sequence'
                                                                        },
                                                                        {
                                                                            xtype: 'menuitem',
                                                                            text: 'Circular View'
                                                                        },
                                                                        {
                                                                            xtype: 'menuitem',
                                                                            text: 'Linear View'
                                                                        }
                                                                    ]
                                                                }
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Edit',
                                                    menu: {
                                                        xtype: 'menu',
                                                        minWidth: 160,
                                                        width: 120,
                                                        items: [
                                                            {
                                                                xtype: 'menuitem',
                                                                id: 'undoMenuItem',
                                                                text: 'Undo'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                id: 'redoMenuItem',
                                                                text: 'Redo'
                                                            },
                                                            {
                                                                xtype: 'menuseparator'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Copy'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Cut'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Paste'
                                                            },
                                                            {
                                                                xtype: 'menuseparator'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                id: 'findMenuItem',
                                                                text: 'Find...'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Go To...'
                                                            },
                                                            {
                                                                xtype: 'menuseparator'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                id: 'selectMenuItem',
                                                                text: 'Select...'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                id: 'selectAllMenuItem',
                                                                text: 'Select All'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                id: 'selectInverseMenuItem',
                                                                text: 'Select Inverse'
                                                            },
                                                            {
                                                                xtype: 'menuseparator'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                itemId: 'reverseComplementMenuItem',
                                                                text: 'Reverse Complement'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                id: 'rebaseMenuItem',
                                                                text: 'Rotate to Here'
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'View',
                                                    menu: {
                                                        xtype: 'menu',
                                                        minWidth: 160,
                                                        items: [
                                                            {
                                                                xtype: 'menucheckitem',
                                                                id: 'circularViewMenuItem',
                                                                text: 'Circular',
                                                                checked: true,
                                                                group: 'lineType'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                id: 'linearViewMenuItem',
                                                                text: 'Linear',
                                                                group: 'lineType'
                                                            },
                                                            {
                                                                xtype: 'menuseparator'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                id: 'featuresMenuItem',
                                                                text: 'Features',
                                                                checked: true
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                id: 'cutSitesMenuItem',
                                                                text: 'Cut Sites'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                id: 'orfsMenuItem',
                                                                text: 'ORF'
                                                            },
                                                            {
                                                                xtype: 'menuseparator'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                id: 'showComplementaryMenuItem',
                                                                text: 'Complementary',
                                                                checked: true
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                id: 'showSpacesMenuItem',
                                                                text: 'Spaces',
                                                                checked: true
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                id: 'showSequenceAAMenuItem',
                                                                text: 'Sequence AA'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                id: 'showRevcomAAMenuItem',
                                                                text: 'Revcom AA'
                                                            },
                                                            {
                                                                xtype: 'menuseparator'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                id: 'featureLabelsMenuItem',
                                                                text: 'Feature Labels',
                                                                checked: true
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                id: 'cutSiteLabelsMenuItem',
                                                                text: 'Cut Site Labels',
                                                                checked: true
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Tools',
                                                    menu: {
                                                        xtype: 'menu',
                                                        minWidth: 150,
                                                        items: [
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Create New Feature'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                id: 'restrictionEnzymesManagerMenuItem',
                                                                text: 'Restriction Enzymes Manager'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                id: 'simulateDigestionMenuItem',
                                                                text: 'Simulate Digestion'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Properties'
                                                            },
                                                            {
                                                                xtype: 'menuseparator'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Preferences'
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Help',
                                                    menu: {
                                                        xtype: 'menu',
                                                        items: [
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Suggest Feature'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Report Bug'
                                                            },
                                                            {
                                                                xtype: 'menuseparator'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'About'
                                                            }
                                                        ]
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'toolbar',
                                            flex: 2,
                                            id: 'VectorEditorMainToolBar',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    id: 'exportBtn',
                                                    icon: 'resources/images/export.png',
                                                    scale: 'medium',
                                                    tooltip: 'Save to Registry'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'saveBtn',
                                                    icon: 'resources/images/save.png',
                                                    scale: 'medium',
                                                    tooltip: 'Save Project'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'projectPropsBtn',
                                                    icon: 'resources/images/project_properties.png',
                                                    scale: 'medium',
                                                    tooltip: 'Project Properties'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'circularViewBtn',
                                                    enableToggle: true,
                                                    icon: 'resources/images/pie.png',
                                                    pressed: true,
                                                    scale: 'medium',
                                                    tooltip: 'Circular View'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'linearViewBtn',
                                                    enableToggle: true,
                                                    icon: 'resources/images/rail.png',
                                                    scale: 'medium',
                                                    tooltip: 'Linear View'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'copyBtn',
                                                    icon: 'resources/images/copy.png',
                                                    scale: 'medium',
                                                    tooltip: 'Copy'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'cutBtn',
                                                    icon: 'resources/images/cut.png',
                                                    scale: 'medium',
                                                    tooltip: 'Cut'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'pasteBtn',
                                                    icon: 'resources/images/paste.png',
                                                    scale: 'medium',
                                                    tooltip: 'Paste'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'undoBtn',
                                                    icon: 'resources/images/undo.png',
                                                    scale: 'medium',
                                                    tooltip: 'Undo'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'redoBtn',
                                                    icon: 'resources/images/redo.png',
                                                    scale: 'medium',
                                                    tooltip: 'Redo'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'safeBtn',
                                                    icon: 'resources/images/safe_editing.png',
                                                    scale: 'medium',
                                                    tooltip: 'Safe Editing'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'findBtn',
                                                    icon: 'resources/images/find.png',
                                                    scale: 'medium',
                                                    tooltip: 'Find...'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'featuresBtn',
                                                    enableToggle: true,
                                                    icon: 'resources/images/features.png',
                                                    pressed: true,
                                                    scale: 'medium',
                                                    tooltip: 'Show Features'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'cutsitesBtn',
                                                    enableToggle: true,
                                                    icon: 'resources/images/cut_sites.png',
                                                    scale: 'medium',
                                                    tooltip: 'Show Cut Sites'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'orfsBtn',
                                                    enableToggle: true,
                                                    icon: 'resources/images/orf.png',
                                                    scale: 'medium',
                                                    tooltip: 'Show ORF'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'reBtn',
                                                    icon: 'resources/images/restriction_enzymes.png',
                                                    scale: 'medium',
                                                    tooltip: 'Show Restriction Enzymes'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'propsBtn',
                                                    icon: 'resources/images/properties.png',
                                                    scale: 'medium',
                                                    tooltip: 'Properties'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    dock: 'bottom',
                                    height: 23,
                                    id: 'StatusPanel',
                                    layout: {
                                        type: 'fit'
                                    },
                                    headerPosition: 'bottom',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            id: 'StatusBar',
                                            items: [
                                                {
                                                    xtype: 'tbfill'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'tbtext',
                                                    text: 'Read only'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'tbspacer',
                                                    width: 10
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'tbtext',
                                                    text: '- : -'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'tbtext',
                                                    text: '0'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'panel',
                                    id: 'VectorEditorPanel',
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            flex: 1,
                                            floating: false,
                                            id: 'VectorPanel',
                                            layout: {
                                                type: 'fit'
                                            },
                                            animCollapse: false,
                                            collapseDirection: 'left',
                                            collapsed: false,
                                            collapsible: true,
                                            title: 'Vector',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    id: 'PieContainer',
                                                    layout: {
                                                        type: 'fit'
                                                    }
                                                },
                                                {
                                                    xtype: 'container',
                                                    hidden: false,
                                                    id: 'RailContainer',
                                                    layout: {
                                                        type: 'fit'
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'splitter',
                                            collapseTarget: 'prev'
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 2,
                                            id: 'AnnotatePanel',
                                            autoScroll: true,
                                            layout: {
                                                type: 'fit'
                                            },
                                            animCollapse: false,
                                            collapsible: false,
                                            title: 'Annotate',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    overflowY: 'scroll',
                                                    id: 'AnnotateContainer',
                                                    layout: {
                                                        type: 'fit'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'DeviceEditorPanel',
                            layout: {
                                type: 'fit'
                            },
                            frameHeader: false,
                            title: 'Device Editor',
                            dockedItems: [
                                {
                                    xtype: 'panel',
                                    dock: 'top',
                                    hidden: false,
                                    id: 'DeviceEditorMenuPanel',
                                    width: 150,
                                    layout: {
                                        type: 'fit'
                                    },
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            id: 'DeviceEditorMenuBar',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'New'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Load',
                                                    menu: {
                                                        xtype: 'menu',
                                                        minWidth: 140,
                                                        width: 140,
                                                        items: [
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Design XML'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'j5 File'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Example Design',
                                                                menu: {
                                                                    xtype: 'menu',
                                                                    minWidth: 220,
                                                                    width: 220,
                                                                    items: [
                                                                        {
                                                                            xtype: 'menuitem',
                                                                            text: 'SLIC/Gibson/CPEC'
                                                                        },
                                                                        {
                                                                            xtype: 'menuitem',
                                                                            text: 'Combinatorial SLIC/Gibson/CPEC'
                                                                        },
                                                                        {
                                                                            xtype: 'menuitem',
                                                                            text: 'Golden Gate'
                                                                        },
                                                                        {
                                                                            xtype: 'menuitem',
                                                                            text: 'Combinatorial Golden Gate'
                                                                        }
                                                                    ]
                                                                }
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Save'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Export'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    dock: 'top',
                                    hidden: false,
                                    id: 'DeviceEditorToolPanel',
                                    width: 150,
                                    layout: {
                                        type: 'fit'
                                    },
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    id: 'add_column_Btn',
                                                    icon: 'resources/images/icons/device/add_column.png',
                                                    scale: 'large',
                                                    tooltip: 'Add Column'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'add_row_Btn',
                                                    icon: 'resources/images/icons/device/add_row.png',
                                                    scale: 'large',
                                                    tooltip: 'Add Row'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 've_init_Btn',
                                                    icon: 'resources/images/icons/device/ve_icon.png',
                                                    scale: 'large',
                                                    tooltip: 'Vector Editor',
                                                    menu: {
                                                        xtype: 'menu',
                                                        id: 'de_ve_menu',
                                                        minWidth: 160,
                                                        width: 120,
                                                        items: [
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Map From Clipboard'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Map From Genbank'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Go To Vector Editor'
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'j5_init_Btn',
                                                    icon: 'resources/images/icons/device/j5_icon.png',
                                                    scale: 'large',
                                                    tooltip: 'j5'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    dock: 'bottom',
                                    height: 23,
                                    id: 'StatusPanel',
                                    layout: {
                                        type: 'fit'
                                    },
                                    headerPosition: 'bottom',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            id: 'StatusBar',
                                            items: [
                                                {
                                                    xtype: 'tbfill'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'tbtext',
                                                    text: 'Read only'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'tbspacer',
                                                    width: 10
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'tbtext',
                                                    text: '- : -'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'tbtext',
                                                    text: '0'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'container',
                                    id: 'DeviceEditorContainer',
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            id: 'DeviceEditorCanvas',
                                            width: 159,
                                            layout: {
                                                type: 'fit'
                                            },
                                            animCollapse: false,
                                            dockedItems: [
                                                {
                                                    xtype: 'panel',
                                                    dock: 'top',
                                                    id: 'DeviceEditorPartPanel',
                                                    collapseDirection: 'top',
                                                    collapsed: true,
                                                    collapsible: true,
                                                    hideCollapseTool: false,
                                                    title: 'Parts',
                                                    titleCollapse: true,
                                                    dockedItems: [
                                                        {
                                                            xtype: 'toolbar',
                                                            dock: 'top',
                                                            height: 45,
                                                            id: 'DeviceEditorPartsBar',
                                                            enableOverflow: true,
                                                            layout: {
                                                                align: 'middle',
                                                                pack: 'center',
                                                                type: 'hbox'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'ori_Btn',
                                                                    icon: 'resources/images/symbols/origin-of-replication.png',
                                                                    scale: 'large',
                                                                    tooltip: 'Origin of Replication'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'cds_Btn',
                                                                    icon: 'resources/images/symbols/cds.png',
                                                                    scale: 'large',
                                                                    tooltip: 'CDS'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'five_prime_ov_Btn',
                                                                    icon: 'resources/images/symbols/five-prime-overhang.png',
                                                                    scale: 'large',
                                                                    tooltip: '5\' Overhang'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'three_prime_ov_Btn',
                                                                    icon: 'resources/images/symbols/three-prime-overhang.png',
                                                                    scale: 'large',
                                                                    tooltip: '3\' Overhang'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'translational_start_site_Btn',
                                                                    icon: 'resources/images/symbols/translational-start-site.png',
                                                                    scale: 'large',
                                                                    tooltip: 'Translational Start Site'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'promoter_Btn',
                                                                    icon: 'resources/images/symbols/promoter.png',
                                                                    scale: 'large',
                                                                    tooltip: 'Promoter'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'primer_binding_site_Btn',
                                                                    icon: 'resources/images/symbols/primer-binding-site.png',
                                                                    scale: 'large',
                                                                    tooltip: 'Primer Binding Site'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'restriction_enz_recog_site_Btn',
                                                                    icon: 'resources/images/symbols/restriction-enzyme-recognition-site.png',
                                                                    scale: 'large',
                                                                    tooltip: 'Restriction Enzyme Recognition Site'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'restriction_site_w_no_overhang_Btn',
                                                                    icon: 'resources/images/symbols/restriction-site-with-no-overhang.png',
                                                                    scale: 'large',
                                                                    tooltip: 'Restriction Site With No Overhangs'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'protease_site_Btn',
                                                                    icon: 'resources/images/symbols/protease-site.png',
                                                                    scale: 'large',
                                                                    tooltip: 'Protease Site'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'protein_stability_element_Btn',
                                                                    icon: 'resources/images/symbols/protein-stability-element.png',
                                                                    scale: 'large',
                                                                    tooltip: 'Protein Stability Element'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'assembly_junction_Btn',
                                                                    icon: 'resources/images/symbols/assembly-junction.png',
                                                                    scale: 'large',
                                                                    tooltip: 'Assembly Junction'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'insulator_Btn',
                                                                    icon: 'resources/images/symbols/insulator.png',
                                                                    scale: 'large',
                                                                    tooltip: 'Insulator'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'operator_Btn',
                                                                    icon: 'resources/images/symbols/operator.png',
                                                                    scale: 'large',
                                                                    tooltip: 'Operator'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'ribonuclease_site_Btn',
                                                                    icon: 'resources/images/symbols/ribonuclease-site.png',
                                                                    scale: 'large',
                                                                    tooltip: 'Ribonuclease Site'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'rna_stability_element_Btn',
                                                                    icon: 'resources/images/symbols/rna-stability-element.png',
                                                                    scale: 'large',
                                                                    tooltip: 'RNA Stability Element'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'terminator_Btn',
                                                                    icon: 'resources/images/symbols/terminator.png',
                                                                    scale: 'large',
                                                                    tooltip: 'Terminator'
                                                                },
                                                                {
                                                                    xtype: 'tbseparator'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'signature_Btn',
                                                                    icon: 'resources/images/symbols/signature.png',
                                                                    params: 'Signature',
                                                                    scale: 'large',
                                                                    tooltip: 'Signature'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ],
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    id: 'designContainer',
                                                    margin: 10
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'tabpanel',
                                            flex: 2,
                                            id: 'InspectorPanel',
                                            maxWidth: 400,
                                            collapseDirection: 'right',
                                            collapsed: false,
                                            collapsible: true,
                                            headerPosition: 'left',
                                            hideCollapseTool: false,
                                            title: 'Inspector',
                                            titleCollapse: true,
                                            activeTab: 0,
                                            minTabWidth: 130,
                                            plain: false,
                                            removePanelHeader: false,
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    layout: {
                                                        align: 'stretch',
                                                        type: 'vbox'
                                                    },
                                                    title: 'Part Info',
                                                    items: [
                                                        {
                                                            xtype: 'form',
                                                            flex: 1,
                                                            height: 160,
                                                            id: 'PartPropertiesForm',
                                                            maxHeight: 170,
                                                            width: 287,
                                                            layout: {
                                                                align: 'stretch',
                                                                type: 'vbox'
                                                            },
                                                            bodyPadding: 10,
                                                            title: 'Properties',
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    id: 'partNameField',
                                                                    fieldLabel: 'Part Name'
                                                                },
                                                                {
                                                                    xtype: 'displayfield',
                                                                    height: 20,
                                                                    id: 'partSourceField',
                                                                    fieldLabel: 'Part Source'
                                                                },
                                                                {
                                                                    xtype: 'displayfield',
                                                                    height: 20,
                                                                    id: 'reverseComplementField',
                                                                    fieldLabel: 'Reverse Complement',
                                                                    labelWidth: 120
                                                                },
                                                                {
                                                                    xtype: 'displayfield',
                                                                    height: 20,
                                                                    id: 'startBPField',
                                                                    fieldLabel: 'Start BP'
                                                                },
                                                                {
                                                                    xtype: 'displayfield',
                                                                    height: 20,
                                                                    id: 'stopBPField',
                                                                    fieldLabel: 'End BP'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'form',
                                                            flex: 1,
                                                            maxHeight: 80,
                                                            bodyPadding: 10,
                                                            title: 'Forced Assembly Strategy',
                                                            items: [
                                                                {
                                                                    xtype: 'combobox',
                                                                    anchor: '100%'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'form',
                                                            flex: 1,
                                                            bodyPadding: 10,
                                                            title: 'Eugene Rules',
                                                            dockedItems: [
                                                                {
                                                                    xtype: 'button',
                                                                    dock: 'top',
                                                                    text: 'Add Rule'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    dock: 'top',
                                                                    text: 'List'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    layout: {
                                                        type: 'fit'
                                                    },
                                                    title: 'Collection Info',
                                                    items: [
                                                        {
                                                            xtype: 'form',
                                                            id: 'collectionInfoForm',
                                                            bodyBorder: false,
                                                            bodyPadding: 10,
                                                            items: [
                                                                {
                                                                    xtype: 'displayfield',
                                                                    anchor: '100%',
                                                                    id: 'j5_ready_field',
                                                                    value: 'Display Field',
                                                                    fieldLabel: 'j5 Ready'
                                                                },
                                                                {
                                                                    xtype: 'displayfield',
                                                                    anchor: '100%',
                                                                    id: 'combinatorial_field',
                                                                    value: 'Display Field',
                                                                    fieldLabel: 'Combinatorial'
                                                                },
                                                                {
                                                                    xtype: 'radiogroup',
                                                                    id: 'plasmid_geometry',
                                                                    fieldLabel: 'Plasmid Type',
                                                                    allowBlank: false,
                                                                    items: [
                                                                        {
                                                                            xtype: 'radiofield',
                                                                            id: 'circular_plasmid_radio',
                                                                            name: 'plasmidtype',
                                                                            boxLabel: 'Circular',
                                                                            checked: true
                                                                        },
                                                                        {
                                                                            xtype: 'radiofield',
                                                                            id: 'linear_plasmid_radio',
                                                                            name: 'plasmidtype',
                                                                            boxLabel: 'Linear'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'gridpanel',
                                                                    margin: 10,
                                                                    autoScroll: true,
                                                                    columnLines: true,
                                                                    columns: [
                                                                        {
                                                                            xtype: 'rownumberer',
                                                                            width: 50,
                                                                            text: 'Column'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            text: 'Direction'
                                                                        },
                                                                        {
                                                                            xtype: 'numbercolumn',
                                                                            text: 'Items'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            text: 'FAS'
                                                                        },
                                                                        {
                                                                            xtype: 'booleancolumn',
                                                                            text: 'DSF'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            text: 'FRO'
                                                                        },
                                                                        {
                                                                            xtype: 'numbercolumn',
                                                                            text: '5\' Ex'
                                                                        },
                                                                        {
                                                                            xtype: 'numbercolumn',
                                                                            text: '3\' Ex'
                                                                        }
                                                                    ],
                                                                    viewConfig: {

                                                                    }
                                                                },
                                                                {
                                                                    xtype: 'container',
                                                                    id: 'inspector_containerActions',
                                                                    margin: 10,
                                                                    items: [
                                                                        {
                                                                            xtype: 'button',
                                                                            text: 'Add Column'
                                                                        },
                                                                        {
                                                                            xtype: 'button',
                                                                            width: 100,
                                                                            text: 'Remove Column'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    anchor: '100%',
                                                                    height: 200,
                                                                    margin: 10,
                                                                    width: 269,
                                                                    fieldLabel: 'Column Content',
                                                                    labelAlign: 'top'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});