/*
 * File: app/view/MyWindow1.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow1', {
    extend: 'Ext.window.Window',

    height: 474,
    width: 551,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: 'Import File',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    flex: 1,
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            flex: 1,
                            items: [
                                {
                                    xtype: 'container',
                                    padding: 3,
                                    layout: {
                                        align: 'stretch',
                                        padding: 3,
                                        type: 'vbox'
                                    },
                                    flex: 1,
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 0.15,
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    fieldLabel: 'Enzymes',
                                                    labelAlign: 'top'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            emptyText: 'Enzyme name',
                                            flex: 0.1
                                        },
                                        {
                                            xtype: 'textareafield',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            flex: 1
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 0.45
                                },
                                {
                                    xtype: 'container',
                                    padding: 3,
                                    layout: {
                                        align: 'stretch',
                                        padding: 3,
                                        type: 'vbox'
                                    },
                                    flex: 1,
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 0.15,
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    fieldLabel: 'Groups',
                                                    labelAlign: 'top'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'textfield',
                                            maxHeight: 153,
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            labelAlign: 'top',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'textareafield',
                                            maxHeight: 180,
                                            fieldLabel: 'Active Enzymes',
                                            labelAlign: 'top',
                                            flex: 1
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            flex: 0.3,
                            items: [
                                {
                                    xtype: 'splitter',
                                    flex: 2
                                },
                                {
                                    xtype: 'button',
                                    margin: 2,
                                    maxHeight: 28,
                                    text: 'MyButton',
                                    flex: 1
                                },
                                {
                                    xtype: 'button',
                                    margin: 2,
                                    maxHeight: 28,
                                    text: 'MyButton',
                                    flex: 1
                                },
                                {
                                    xtype: 'button',
                                    margin: 2,
                                    maxHeight: 28,
                                    text: 'MyButton',
                                    flex: 1
                                },
                                {
                                    xtype: 'button',
                                    margin: 2,
                                    maxHeight: 28,
                                    text: 'MyButton',
                                    flex: 1
                                },
                                {
                                    xtype: 'splitter',
                                    flex: 3
                                },
                                {
                                    xtype: 'button',
                                    margin: 2,
                                    maxHeight: 28,
                                    text: 'MyButton',
                                    flex: 1
                                },
                                {
                                    xtype: 'button',
                                    margin: 2,
                                    maxHeight: 28,
                                    text: 'MyButton',
                                    flex: 1
                                },
                                {
                                    xtype: 'splitter',
                                    flex: 2
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: '',
                    padding: 2,
                    layout: {
                        align: 'stretch',
                        padding: '',
                        type: 'hbox'
                    },
                    flex: 0.1,
                    items: [
                        {
                            xtype: 'splitter',
                            width: 350
                        },
                        {
                            xtype: 'button',
                            height: 23,
                            margin: 2,
                            maxHeight: 28,
                            padding: '',
                            text: 'MyButton',
                            flex: 1
                        },
                        {
                            xtype: 'button',
                            margin: 2,
                            maxHeight: 28,
                            text: 'MyButton',
                            flex: 1
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});