/*
 * File: app/view/ProjectManagerWindow.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vesa.view.ProjectManagerWindow', {
    extend: 'Ext.window.Window',

    height: 250,
    id: 'ProjectManagerWindow',
    width: 400,
    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    title: 'Project Manager',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 2,
                    id: 'projectGrid_Panel',
                    title: 'Your Projects',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            id: 'projectGrid_name',
                            dataIndex: 'string',
                            text: 'Name'
                        },
                        {
                            xtype: 'datecolumn',
                            id: 'projectGrid_DateCreated',
                            dataIndex: 'date',
                            text: 'Date Created'
                        },
                        {
                            xtype: 'datecolumn',
                            id: 'projectGrid_DateModified',
                            dataIndex: 'date',
                            text: 'Last Modified'
                        }
                    ],
                    viewConfig: {

                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    flex: 1,
                    items: [
                        {
                            xtype: 'button',
                            text: 'New Project'
                        },
                        {
                            xtype: 'button',
                            text: 'Delete Project'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});