/*
 * File: app/controller/GenbankCleanerUtil.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TeselagenUtils.controller.GenbankCleanerUtil', {
    extend: 'Ext.app.Controller',
    requires: ["TeselagenUtils.manager.gbCleanerManager"],

    oncleanAndDownloadBtnClick: function(btn){
        var form = btn.up('form').getForm();
        var fileField = form.findField('importedFile');

        if(!fileField.inputEl.dom.value) return Ext.MessageBox.alert('Error', 'First select a file.');

        processText =  function(){
            var data = fr.result;
            TeselagenUtils.manager.gbCleanerManager.processGenbankFile(file,data);
        };

        var fileInput = fileField.extractFileInput();
        file = fileInput.files[0];
        fr = new FileReader();
        fr.onload = processText;
        fr.readAsText(file);

        

        //fileInput.fileInputEl.dom.value = fileInput.fileInputEl.dom.value.replace("C:\\fakepath\\", "");

        

    },

    init: function () {
        this.callParent();
        this.control({
            "#cleanAndDownloadBtn": {
                click: this.oncleanAndDownloadBtnClick
            }
        });
    }
});
