/*
 * File: app/controller/MainMenuController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.controller.MainMenuController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'importWin',
            selector: '#importWin'
        }
    ],

    onImportMenuItemClick: function(item, e, options) {
        Ext.create("App.view.FileImportWindow").show();
    },

    onCancelButtonClick: function(button, e, options) {
        button.up('window').close();
    },

    onImportButtonClick: function(button, e, options) {
        if (typeof window.FileReader !== 'function') {
            Ext.Msg.alert('Browser does not support File API.');
        }
        else {
            var form = button.up('form').getForm();
            var fileField = form.findField('importedFile');
            var fileInput = fileField.extractFileInput();
            var file = fileInput.files[0];
            fr = new FileReader();
            fr.onload = processText;
            fr.readAsText(file);
        }
        button.up('window').close();

        function processText() {
            var result = fr.result;
            var gb = Ext.create('Teselagen.Genbank', result);
            console.log(gb);
        }
    },

    onControllerClickStub: function() {

    },

    init: function() {
        this.control({
            "#importMenuItem": {
                click: this.onImportMenuItemClick
            },
            "button[text=Cancel]": {
                click: this.onCancelButtonClick
            },
            "button[text='Import']": {
                click: this.onImportButtonClick
            }
        });

    }

});
