/*
 * File: app/controller/VectorPanelController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.VectorPanelController', {
    extend: 'Ext.app.Controller',

    onLaunch: function() {
        var vp = Ext.getCmp("VectorPanel");
        var drawComponent = Ext.create('Ext.draw.Component', {
            items: [{
                type: 'circle',
                fill: '#79BB3F',
                radius: 100,
                x: 100,
                y: 100
            }, {
                type: 'path',
                path: 'M 0 0 L 100 100',
                stroke: 'black' 
            }]
        });
        vp.add(drawComponent);
        //drawComponent.surface.add({
        //    type: 'path',
        //    path: 'M 10 10 L 100 100'
        //});
        //drawComponent.surface.redraw();
    }

});
