/*
 * File: app/controller/ActionStackController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Vesa.controller.ActionStackController', {
    extend: 'Ext.app.Controller',

    requires: [
        'Teselagen.event.MenuItemEvent',
        'Teselagen.event.SequenceManagerEvent'
    ],

    init: function(application) {
        this.MenuItemEvent = Teselagen.event.MenuItemEvent;
        this.SequenceManagerEvent = Teselagen.event.SequenceManagerEvent;

        this.application.on(this.SequenceManagerEvent.SEQUENCE_MANAGER_CHANGED,
        this.onSequenceManagerChanged, this);

        this.application.on(this.SequenceManagerEvent.SEQUENCE_CHANGING,
        this.onSequenceChanging, this);

        this.application.on(this.MenuItemEvent.UNDO,
        this.onUndo, this);
        this.application.on(this.MenuItemEvent.REDO,
        this.onRedo, this);

    },

    onLaunch: function() {
        this.ActionStackManager = Ext.create("Teselagen.manager.ActionStackManager");

    },

    onSequenceManagerChanged: function(pSeqMan) {
        this.SequenceManager = pSeqMan;
        this.ActionStackManager.setSequenceManager(pSeqMan);
        this.ActionStackManager.clear();

    },

    onSequenceChanging: function(kind, memento) {
        console.log("adding memento");
        this.ActionStackManager.add(memento);

    },

    onUndo: function() {
        if(this.SequenceManager && this.ActionStackManager.undoStack.length != 0) {
            this.ActionStackManager.undo();
        }

    },

    onRedo: function() {
        if(this.SequenceManager && this.ActionStackManager.redoStack.length != 0) {
            this.ActionStackManager.redo();
        }

    }

});
