/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

var myMask;
Ext.onReady(function() {
myMask = new Ext.LoadMask(Ext.getBody(), {msg:"Please wait..."});
myMask.show();
});

Ext.Loader.setConfig({
    enabled: true,
    paths: {
        Ext: '.',
        Teselagen: './app/teselagen'
    }
});

Ext.application({
    views: [
        'AppViewport',
        'FileImportWindow',
        'SimulateDigestionWindow',
        'RestrictionEnzymesManagerWindow'
    ],
    autoCreateViewport: true,
    name: 'MyApp',
    controllers: [
        'MainMenuController',
        'MainToolbarController',
        'VectorPanelController',
        'MyApp.controller.DeviceEditor.MainMenuController',
        'MyApp.controller.DeviceEditor.MainToolbarController',
        'MyApp.controller.DeviceEditor.DeviceEditorPanelController'
    ]
});
