/*
 * File: app/view/SimulateDigestionWindow.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
//Ext.Loader.setConfig({enabled: true});
/*Ext.require([
    'Ext.form.Panel',
    'Ext.ux.form.MultiSelect',
    'Ext.ux.form.ItemSelector'
]);*/
Ext.define('Vede.view.SimulateDigestionWindow', {
    extend: 'Ext.window.Window',
    requires: ['Ext.form.Panel', 'Ext.ux.form.MultiSelect', 'Ext.ux.form.ItemSelector'],
    height: 500,
    width: 900,
    resizable: false,
    title: 'Gel Digest',
    id: "simulateDigestionWindow",
    resizable: false,
    modal: true,
    //var enzymeStore = 
    initComponent: function() {
        var me = this;
var possibleEnzymes = new Ext.data.Store({
   // store configs
            autoLoad: true,
   autoDestroy: true,
   storeId: 'initialEnzymes',
   // reader configs
   fields: [
            {name : 'id', type : 'int'},
      {name: 'name', type: 'string'}
   ],
    data: [
    {"id": 0,"name": "Common"},
    ]
});

        var initialEnzymes = new Ext.data.Store({
   // store configs
            autoLoad: true,
   autoDestroy: true,
   storeId: 'initialEnzymes',
   // reader configs
   fields: [
            {name : 'id', type : 'int'},
      {name: 'name', type: 'string'}
   ],
    data: [
    {"id": 0,"name": "Common"},
    {"id": 1,"name": "REBASE"},
    {"id": 2,"name": "Berkeley BioBricks"},
    {"id": 3,"name": "MIT BioBricks"},
    {"id": 4,"name": "Fermentas Fast Digest"}
    ]
});
                Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'container',
                    height: 470,
                    width: 500,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            width: 500,
                            title: 'Enzymes', 
                            flex: 1,
                            layout: {
                                type: 'absolute'
                            } ,
                            items: [
                                {
                                    xtype: 'combobox',
                                    id: 'enzymeGroupSelector',
                                    width: 195,
                                    fieldLabel: '',
                                    editable: false,
                                    displayField: 'name',
                                    valueField: 'name',
                                    store: initialEnzymes, //change this store to query database
                                    value: 'Common',
                                    listeners: { 
                                        select: function(combo, newvalue, oldvalue){
                                            var newGroup = combo.getValue();
                                            var reGroupManager = Ext.create("Teselagen.manager.RestrictionEnzymeGroupManager", {});
                                            reGroupManager.initialize();
                                            var retrievedGroup = reGroupManager.groupByName(newGroup);
                                            console.log(retrievedGroup.getName());
                                            var cmp = Ext.getCmp('itemselector-field');
                                            console.log(cmp.store.getAt(0));
                                            cmp.store.removeAll(true);-
                                            console.log(cmp.store.getAt(0));
                                            cmp.store.add([newGroup]);
                                        }
                                    },
                                    x: 10,
                                    y: 10
                                },
                                {
                                    xtype: 'combobox',
                                    width: 195,
                                    hideTrigger: true,
                                    value: 'Search enzymes',
                                    store: ['AatII', 'Acc65I', 'AccI', 'Not', 'Bam', 'XhoI'], //change this to query database
                                    fieldLabel: '',
                                    hideLabel: true,
                                    triggerAction: 'query',
                                    typeAhead: true,
                                    //disabled: true,
                                    x: 235,
                                    y: 10
                                },
                                {
                                   xtype: 'itemselector', 
                    title: "Enzymes",
                    height: 400,
                    width: 420,
        id: 'itemselector-field',
                    imagePath: '../../extjs/examples/ux/css/images/',
        store: possibleEnzymes,
        autoShow: true,
        displayField: 'name',
        valueField: 'name',
        allowBlank: false,
        msgTarget: 'side',
        x: 10,
        y: 40
                                    
                                }
                            ] 
                        },
                        
                        {
                            xtype: 'panel',
                            height: 500,
                            width: 300,
                            layout: {
                                align: 'middle',
                                type: 'hbox'
                            },
                            dock: 'right',
                            title: 'Digest Results',
                            flex: 1,
                        
                            dockedItems: [
                        {
                            xtype: 'container',
                            height: 400,
                            width: 460,
                            layout: {
                                align: 'middle',
                                type: 'hbox'
                            },
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 400,
                                    width: 400,
                                    layout: {
                                        type: 'absolute'
                                    },
                                    flex: 1,
                                    items: [{
                                        xtype: 'draw',
                                        id: 'drawingSurface',
                                            items: [{
                                                type: 'rect',
                                                fill: '#000',
                                                width: 400,
                                                height: 400,
                                                x: 0,
                                                y: 0
                                            }]
                                    }]
                                },
                            ]
                        }
                    ],
                        
                       items: [
                        {
                            xtype: 'fieldcontainer',
                            height: 40,
                            padding: '10 0 30 10',
                            width: 400,
                            fieldLabel: '',
                            items: [
                                {
                                    xtype: 'combobox',
                                    height: 21,
                                    padding: ' 10 0 0 10',
                                    width: 327,
                                    value: 'GeneRuler 1kb Plus DNA',
                                    store: ['GeneRuler 1kb Plus DNA', 'GeneRuler 100bp Plus DNA'],
                                    fieldLabel: 'Ladder',
                                    listeners: { 
                                        select: function(combo, record, index){
                                           me.changeLadder(combo,record, index); 
                                        }
                                    },

                                    labelWidth: 50
                                }
                            ]
                        }
                    ] 
                        //
                        }
                    ]
                }
            ]
        });
        me.callParent(arguments);
    },

    updateEnzymeList: function(combo, newvalue, oldvalue){
        console.log(combo.getValue());
    },

    changeLadder: function(combo, record, index){
        console.log("Ladder changed");
    }
});
