/*
 * File: app/view/SimulateDigestionWindow.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
//Ext.Loader.setConfig({enabled: true});
/*Ext.require([
    'Ext.form.Panel',
    'Ext.ux.form.MultiSelect',
    'Ext.ux.form.ItemSelector'
]);*/
Ext.define('Vede.view.SimulateDigestionWindow', {
    extend: 'Ext.window.Window',

    height: 500,
    width: 900,
    resizable: false,
    title: 'Gel Digest',
    id: "simulateDigestionWindow",
    resizable: false,
    modal: true,
    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'container',
                    height: 650,
                    width: 200,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    dock: 'left',
                    items: [
                        {
                            xtype: 'panel',
                            width: 200,
                            layout: {
                                type: 'absolute'
                            },
                            title: 'Enzymes',
                            flex: 1,
                            items: [
                                {
                                    xtype: 'combobox',
                                    width: 180,
                                    fieldLabel: '',
                                    x: 10,
                                    y: 10
                                },
                                {
                                    xtype: 'textfield',
                                    width: 180,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    x: 10,
                                    y: 40
                                },
                                {
                                    xtype: 'fieldset',
                                    height: 380,
                                    width: 200,
                                    title: '',
                                    x: 0,
                                    y: 70
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    height: 658,
                    width: 131,
                    layout: {
                        type: 'absolute'
                    },
                    fieldLabel: '',
                    dock: 'left',
                    items: [
                        {
                            xtype: 'button',
                            height: 22,
                            width: 103,
                            text: '>',
                            x: 15,
                            y: 210
                        },
                        {
                            xtype: 'button',
                            height: 22,
                            width: 103,
                            text: '<',
                            x: 15,
                            y: 320
                        },
                        {
                            xtype: 'button',
                            height: 22,
                            width: 103,
                            text: '<<',
                            x: 15,
                            y: 345
                        },
                        {
                            xtype: 'button',
                            height: 22,
                            width: 103,
                            text: '>>',
                            x: 15,
                            y: 235
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    width: 195,
                    title: 'Active Enzymes',
                    dock: 'left'
                },/*
                {
                    xtype: 'splitter',
                    dock: 'left'
                }*/
            ],
            
            items: [
                {
                    xtype: 'panel',
                    height: 656,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    title: 'Simulated Digestion Results',
                    dockedItems: [
                        {
                            xtype: 'container',
                            height: 600,
                            width: 460,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            flex: 10,
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1
                                },
                                {
                                    xtype: 'container',
                                    flex: 1
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            height: 56,
                            width: 450,
                            fieldLabel: '',
                            items: [
                                {
                                    xtype: 'combobox',
                                    width: 437,
                                    fieldLabel: 'Ladder'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});
