
module.exports.seq1 = '{"sequence":"GATAGCTAGCATGCGGGCAAATTTGCGATGCA","features":[{"name":"feature 1","start":2,"end":7},{"name":"feature 2","start":12,"end":22},{"name":"feature 3","start":15,"end":20}]}';
module.exports.device1 = '{"name":"Test Device 01","bins":[{"name":"Bin 1","icon":"a","dsf":false,"dir":true,"cells":[{"phantom":true},{"phantom":false,"partId":40,"part":{"id":40,"name":"Part A"}}]},{"name":"Bin 2","icon":"b","dsf":false,"dir":true,"cells":[{"phantom":false,"partId":41,"part":{"id":41,"name":"Part B"}},{"phantom":true}]}],"parts":[{"id":40,"name":"Part A"},{"id":41,"name":"Part B"}],"rules":[],"partIdMap":{"40":{"id":40,"name":"Part A"},"41":{"id":41,"name":"Part B"}}}';




































