//Need to implement  singleton

Ext.define("Teselagen.bio.sequence.alphabets.RNAAlphabet", {
	extend: "Teselagen.bio.sequence.alphabets.AbstractAlphabet",
      singleton: true,

	a: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Adenine", value: "a", ambiguousMatches: ""}),
        g: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Guanine", value: "g", ambiguousMatches: ""}), 
        c: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Cytosine", value: "c", ambiguousMatches: ""}), 
        u: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Uracil", value: "u", ambiguousMatches: ""}),
        m: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Ambiguous {'a' or 'c'}", value: "m", ambiguousMatches: [this.a, this.c]}), 
        r: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Ambiguous {'a' or 'g'}", value: "r", ambiguousMatches: [this.a, this.g]}), 
        w: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Ambiguous {'a' or 'u'}", value: "s", ambiguousMatches: [this.a, this.u]}), 
        s: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Ambiguous {'c' or 'g'}", value: "s", ambiguousMatches: [this.c, this.g]}), 
        y: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Ambiguous {'c' or 'u'}", value: "y", ambiguousMatches: [this.c, this.u]}), 
        k: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Ambiguous {'g' or 'u'}", value: "k", ambiguousMatches: [this.g, this.u]}), 
        v: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Ambiguous {'a' or 'c' or 'g'}", value: "v", ambiguousMatches: [this.a, this.c, this.g]}),
        h: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Ambiguous {'a' or 'c' or 'u'}", value: "h", ambiguousMatches: [this.a, this.c, this.u]}), 
        d: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Ambiguous {'a' or 'g' or 'u'}", value: "d", ambiguousMatches: [this.a, this.g, this.u]}),
        b: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Ambiguous {'c' or 'g' or 'u'}", value: "b", ambiguousMatches: [this.c, this.g, this.u]}), 
        n: Ext.create("Teselagen.bio.sequence.symbols.NucleotideSymbol", {name: "Ambiguous {'a' or 'u' or 'g' or 'c'}", value: "n", ambiguousMatches: [this.a, this.c, this.g, this.u]}),
        
        getA: function (){ return this.a; },
       getG: function (){ return this.g; },
       getC: function (){ return this.c; },
       getU: function (){ return this.u; },
       getM: function (){ return this.m; },
       getR: function (){ return this.r; },
       getW: function (){ return this.w; },
       getS: function (){ return this.s; },
       getY: function (){ return this.y; },
       getK: function (){ return this.k; },
       getV: function (){ return this.v; },
       getH: function (){ return this.h; },
       getD: function (){ return this.d; },
       getB: function (){ return this.b; },
       getN: function (){ return this.n; },
});